sudo: required

language: python

python:
- '2.7'

before_install:
- sudo apt-get update
- sudo pip install -U pip
- sudo pip install -r requirements.txt
- sudo apt-get install python-pyaudio


install:
- python setup.py bdist_wheel
- sudo pip install ./dist/*.whl

script:
- pytest