sudo: required

language: python

python:
- '2.7'

before_install:
- sudo apt-get update
- sudo apt-get install python-pyaudio
- sudo apt-get install libsamplerate0

install:
- python setup.py bdist_wheel
- pip install ./dist/*.whl

script:
- pytest