sudo: required

language: python

python:
- '2.7'

before_install:
- sudo apt-get update
- sudo apt-get install python-pyaudio
- sudo pip install -U pip

install:
- python setup.py bdist_wheel
- sudo pip install ./dist/*.whl

script:
- pytest